# coding=utf-8
# Copyright 2024 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

read_root: data/raw/MSCOCO/images/val2017/*
filter_file: annotations/MSCOCO-val2017_demo.json
aggregation_ckpt: weights/readout_sdv15_pose_keypoint.pt
detector_ckpt: yolov8s
save_root: data/pseudo_labels/MSCOCO/readout_pose_keypoint
batch_size: 5
res: 512